apiVersion: v1
kind: Service
metadata:
  name: ejs-viewer-service
spec:
  selector:
    app: ejs-viewer
  type: NodePort
  ports:
    - name: frontend
      protocol: TCP
      port: 5173
      targetPort: 5173
    - name: backend
      protocol: TCP
      port: 5174
      targetPort: 5174
